# Generated by Django 3.1.2 on 2022-10-29 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmanager',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentmanager',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DepartmentEmployee',
        ),
        migrations.DeleteModel(
            name='DepartmentManager',
        ),
    ]
