# Generated by Django 3.1.2 on 2022-10-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221029_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_employees',
            field=models.ManyToManyField(blank=True, related_name='dept_emps', to='accounts.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to='accounts.employee'),
        ),
    ]
