# Generated by Django 3.1.2 on 2022-12-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221029_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=265)),
                ('proj_employees', models.ManyToManyField(blank=True, null=True, related_name='project_employees', to='accounts.Employee')),
                ('proj_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_leader', to='accounts.employee')),
            ],
        ),
    ]
